#docker compose version to run the api locally and the database in docker
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: open_ecommerce_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: open_ecommerce_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: open_ecommerce_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin@admin.com
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - nest_network

networks:
  nest_network:

volumes:
  postgres_data: